services:
  mqtt_broker:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001" # WebSocket port if needed
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
